### ISSUE TITLE
xsel: command not found

### ISSUE THREAD

**Issue by Enissay** [CopyText/TextCopy#532]
I am getting this error when trying to `ClipboardService.SetText(result);`

.Net: 6.0
OS: Ubuntu 20.04

```
System.Exception: Could not execute process. Command line: bash -c "cat /tmp/tmpc9A2GC.tmp | xsel -i --clipboard ".
Output: 

Error: bash: xsel: command not found
cat: write error: Broken pipe

   at BashRunner.Run(String commandLine) in /_/src/TextCopy/BashRunner.cs:line 42
   at LinuxClipboard.InnerSetText(String tempFileName) in /_/src/TextCopy/LinuxClipboard_2.1.cs:line 42
   at LinuxClipboard.SetText(String text) in /_/src/TextCopy/LinuxClipboard_2.1.cs:line 29
   at TextCopy.ClipboardService.SetText(String text) in /_/src/TextCopy/ClipboardService.cs:line 61

```

**Comment by SimonCropp** [comment]
https://github.com/CopyText/TextCopy#linux
