### ISSUE TITLE
Doesn't work on Arch based Linux distro

### ISSUE THREAD

**Issue by dement6d** [CopyText/TextCopy#558]
xsel isn't installed but xcopy is

```
Unhandled exception. System.Exception: Could not execute process. Command line: bash -c "cat /tmp/tmpH2iy3e.tmp | xsel -i --clipboard ".
Output: 

Error: bash: line 1: xsel: command not found
cat: write error: Broken pipe


   at BashRunner.Run(String commandLine) in /_/src/TextCopy/BashRunner.cs:line 42
   at LinuxClipboard.InnerSetText(String tempFileName) in /_/src/TextCopy/LinuxClipboard_2.1.cs:line 42
   at LinuxClipboard.SetText(String text) in /_/src/TextCopy/LinuxClipboard_2.1.cs:line 29
   at TextCopy.ClipboardService.SetText(String text) in /_/src/TextCopy/ClipboardService.cs:line 61
   at Program.<Main>$(String[] args)```

**Comment by SimonCropp** [comment]
https://github.com/CopyText/TextCopy#linux
