### ISSUE TITLE
Clipboard functionality not working in Linux (jenkins - kubernetes)

### ISSUE THREAD

**Issue by Kalyan7829** [CopyText/TextCopy#699]
Hello,

I am trying to use the TextCopy library for copying to the clipboard.

I am getting the below error while running it through jenkins.

logs -

 ```
Error Message:
2023-05-25 11:09:22.472 |      System.Exception : Could not execute process. Command line: bash -c "cat /tmp/tmpt3ouhj.tmp | xsel -i --clipboard ".
2023-05-25 11:09:22.472 |   Output: 
2023-05-25 11:09:22.472 |   
2023-05-25 11:09:22.472 |   Error: bash: line 1: xsel: command not found
2023-05-25 11:09:22.472 |   cat: write error: Broken pipe
2023-05-25 11:09:22.472 |   
2023-05-25 11:09:22.472 |   
2023-05-25 11:09:22.472 |     Stack Trace:
2023-05-25 11:09:22.472 |        at BashRunner.Run(String commandLine) in /_/src/TextCopy/BashRunner.cs:line 42
2023-05-25 11:09:22.472 |      at LinuxClipboard.InnerSetText(String tempFileName) in /_/src/TextCopy/LinuxClipboard_2.1.cs:line 42
2023-05-25 11:09:22.472 |      at LinuxClipboard.SetText(String text) in /_/src/TextCopy/LinuxClipboard_2.1.cs:line 29
2023-05-25 11:09:22.472 |      at TextCopy.ClipboardService.SetText(String text) in /_/src/TextCopy/ClipboardService.cs:line 61
```

Could you pls help me on this issue.

the library is working fine in Windows machine.

Thanks in advance!

**Comment by SimonCropp** [comment]
https://github.com/CopyText/TextCopy#linux

**Comment by Kalyan7829** [comment]
@SimonCropp , can you pls elaborate on the steps.

**Comment by SimonCropp** [comment]
> Linux uses [xsel](https://github.com/kfish/xsel) to access the clipboard. As such it needs to be installed and callable.

not sure how to elaborate?
