### ISSUE TITLE
xsel: command not found

### ISSUE THREAD

**Issue by dylanvdmerwe** [CopyText/TextCopy#733]
On Ubuntu 22.04, using the following command in .Net 7 console project causes an exception. 

`TextCopy.ClipboardService.SetText(hashed);`

```
System.Exception: Could not execute process. Command line: bash -c "cat /tmp/tmpySP8ZA.tmp | xsel -i --clipboard ".
Output: 

Error: bash: line 1: xsel: command not found
cat: write error: Broken pipe


   at BashRunner.Run(String commandLine) in /_/src/TextCopy/BashRunner.cs:line 42
   at LinuxClipboard.InnerSetText(String tempFileName) in /_/src/TextCopy/LinuxClipboard_2.1.cs:line 42
   at LinuxClipboard.SetText(String text) in /_/src/TextCopy/LinuxClipboard_2.1.cs:line 29
   at TextCopy.ClipboardService.SetText(String text) in /_/src/TextCopy/ClipboardService.cs:line 61
```

Is there no other way to achieve this without having to install the missing package?

**Comment by SimonCropp** [comment]
> Is there no other way to achieve this without having to install the missing package

not that i know of
